/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThirdPartyBrandsIndexRouteImport } from './routes/third-party-brands/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as RegisterCompleteRouteImport } from './routes/register/complete'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as ThirdPartyBrandsTrademarksIndexRouteImport } from './routes/third-party-brands/trademarks/index'
import { Route as ThirdPartyBrandsReportIdIndexRouteImport } from './routes/third-party-brands/$reportId/index'
import { Route as ThirdPartyBrandsReportIdProcessIdRouteImport } from './routes/third-party-brands/$reportId/$processId'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThirdPartyBrandsIndexRoute = ThirdPartyBrandsIndexRouteImport.update({
  id: '/third-party-brands/',
  path: '/third-party-brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCompleteRoute = RegisterCompleteRouteImport.update({
  id: '/register/complete',
  path: '/register/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const ThirdPartyBrandsTrademarksIndexRoute =
  ThirdPartyBrandsTrademarksIndexRouteImport.update({
    id: '/third-party-brands/trademarks/',
    path: '/third-party-brands/trademarks/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThirdPartyBrandsReportIdIndexRoute =
  ThirdPartyBrandsReportIdIndexRouteImport.update({
    id: '/third-party-brands/$reportId/',
    path: '/third-party-brands/$reportId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ThirdPartyBrandsReportIdProcessIdRoute =
  ThirdPartyBrandsReportIdProcessIdRouteImport.update({
    id: '/third-party-brands/$reportId/$processId',
    path: '/third-party-brands/$reportId/$processId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/third-party-brands/': typeof ThirdPartyBrandsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/third-party-brands/$reportId/$processId': typeof ThirdPartyBrandsReportIdProcessIdRoute
  '/third-party-brands/$reportId/': typeof ThirdPartyBrandsReportIdIndexRoute
  '/third-party-brands/trademarks/': typeof ThirdPartyBrandsTrademarksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/dashboard': typeof DashboardIndexRoute
  '/register': typeof RegisterIndexRoute
  '/third-party-brands': typeof ThirdPartyBrandsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/third-party-brands/$reportId/$processId': typeof ThirdPartyBrandsReportIdProcessIdRoute
  '/third-party-brands/$reportId': typeof ThirdPartyBrandsReportIdIndexRoute
  '/third-party-brands/trademarks': typeof ThirdPartyBrandsTrademarksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/register/complete': typeof RegisterCompleteRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/third-party-brands/': typeof ThirdPartyBrandsIndexRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/third-party-brands/$reportId/$processId': typeof ThirdPartyBrandsReportIdProcessIdRoute
  '/third-party-brands/$reportId/': typeof ThirdPartyBrandsReportIdIndexRoute
  '/third-party-brands/trademarks/': typeof ThirdPartyBrandsTrademarksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/register/complete'
    | '/dashboard/'
    | '/register/'
    | '/third-party-brands/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/third-party-brands/$reportId/$processId'
    | '/third-party-brands/$reportId/'
    | '/third-party-brands/trademarks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/register/complete'
    | '/dashboard'
    | '/register'
    | '/third-party-brands'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/third-party-brands/$reportId/$processId'
    | '/third-party-brands/$reportId'
    | '/third-party-brands/trademarks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/register/complete'
    | '/dashboard/'
    | '/register/'
    | '/third-party-brands/'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/third-party-brands/$reportId/$processId'
    | '/third-party-brands/$reportId/'
    | '/third-party-brands/trademarks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  RegisterCompleteRoute: typeof RegisterCompleteRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ThirdPartyBrandsIndexRoute: typeof ThirdPartyBrandsIndexRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  ThirdPartyBrandsReportIdProcessIdRoute: typeof ThirdPartyBrandsReportIdProcessIdRoute
  ThirdPartyBrandsReportIdIndexRoute: typeof ThirdPartyBrandsReportIdIndexRoute
  ThirdPartyBrandsTrademarksIndexRoute: typeof ThirdPartyBrandsTrademarksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party-brands/': {
      id: '/third-party-brands/'
      path: '/third-party-brands'
      fullPath: '/third-party-brands/'
      preLoaderRoute: typeof ThirdPartyBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/complete': {
      id: '/register/complete'
      path: '/register/complete'
      fullPath: '/register/complete'
      preLoaderRoute: typeof RegisterCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party-brands/trademarks/': {
      id: '/third-party-brands/trademarks/'
      path: '/third-party-brands/trademarks'
      fullPath: '/third-party-brands/trademarks/'
      preLoaderRoute: typeof ThirdPartyBrandsTrademarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party-brands/$reportId/': {
      id: '/third-party-brands/$reportId/'
      path: '/third-party-brands/$reportId'
      fullPath: '/third-party-brands/$reportId/'
      preLoaderRoute: typeof ThirdPartyBrandsReportIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/third-party-brands/$reportId/$processId': {
      id: '/third-party-brands/$reportId/$processId'
      path: '/third-party-brands/$reportId/$processId'
      fullPath: '/third-party-brands/$reportId/$processId'
      preLoaderRoute: typeof ThirdPartyBrandsReportIdProcessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  RegisterCompleteRoute: RegisterCompleteRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ThirdPartyBrandsIndexRoute: ThirdPartyBrandsIndexRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  ThirdPartyBrandsReportIdProcessIdRoute:
    ThirdPartyBrandsReportIdProcessIdRoute,
  ThirdPartyBrandsReportIdIndexRoute: ThirdPartyBrandsReportIdIndexRoute,
  ThirdPartyBrandsTrademarksIndexRoute: ThirdPartyBrandsTrademarksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
